// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: oberon.flex

import exceptions.*;
import java_cup.runtime.*;
import java.io.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class OberonScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\121\u1100\1\u2700\4\u1100\1\u2800"+
    "\1\u1100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\1\u2e00\53\u1100"+
    "\1\u2f00\41\u2000\1\u1100\1\u3000\1\u3100\1\u1100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u2000\1\u3600\1\u3700\1\u3800\1\u3900\1\u1100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u2000"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u2000\1\u4d00\1\u4e00\1\u4f00"+
    "\1\u2000\3\u1100\1\u5000\1\u5100\1\u5200\12\u2000\4\u1100\1\u5300"+
    "\17\u2000\2\u1100\1\u5400\41\u2000\2\u1100\1\u5500\1\u5600\2\u2000"+
    "\1\u5700\1\u5800\27\u1100\1\u5900\2\u1100\1\u5a00\45\u2000\1\u1100"+
    "\1\u5b00\1\u5c00\11\u2000\1\u5d00\27\u2000\1\u5e00\1\u5f00\1\u6000"+
    "\1\u6100\11\u2000\1\u6200\1\u6300\5\u2000\1\u6400\1\u6500\4\u2000"+
    "\1\u6600\21\u2000\246\u1100\1\u6700\20\u1100\1\u6800\1\u6900\25\u1100"+
    "\1\u6a00\34\u1100\1\u6b00\14\u2000\2\u1100\1\u6c00\u0e05\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\2\0\1\4\2\0\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\0\1\15\7\16\2\17"+
    "\1\20\1\21\1\22\1\23\1\24\2\0\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\36\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\36\1\52\1\36\1\53"+
    "\1\0\1\54\3\0\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\2\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\36\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\36\1\52\1\36\3\0\1\55\53\0\1\36"+
    "\12\0\1\36\4\0\1\36\5\0\27\36\1\0\37\36"+
    "\1\0\70\36\2\35\115\36\1\45\u0142\36\4\0\14\36"+
    "\16\0\5\36\7\0\1\36\1\0\1\36\201\0\5\36"+
    "\1\0\2\36\2\0\4\36\1\0\1\36\6\0\1\36"+
    "\1\0\3\36\1\0\1\36\1\0\24\36\1\0\123\36"+
    "\1\0\213\36\10\0\246\36\1\0\46\36\2\0\1\36"+
    "\6\0\51\36\107\0\33\36\4\0\4\36\55\0\53\36"+
    "\25\0\12\56\4\0\2\36\1\0\143\36\1\0\1\36"+
    "\17\0\2\36\7\0\2\36\12\56\3\36\2\0\1\36"+
    "\20\0\1\36\1\0\36\36\35\0\131\36\13\0\1\36"+
    "\16\0\12\56\41\36\11\0\2\36\4\0\1\36\5\0"+
    "\26\36\4\0\1\36\11\0\1\36\3\0\1\36\27\0"+
    "\31\36\7\0\13\36\65\0\25\36\1\0\10\36\106\0"+
    "\66\36\3\0\1\36\22\0\1\36\7\0\12\36\4\0"+
    "\12\56\1\0\20\36\4\0\10\36\2\0\2\36\2\0"+
    "\26\36\1\0\7\36\1\0\1\36\3\0\4\36\3\0"+
    "\1\36\20\0\1\36\15\0\2\36\1\0\3\36\4\0"+
    "\12\56\2\36\12\0\1\36\10\0\6\36\4\0\2\36"+
    "\2\0\26\36\1\0\7\36\1\0\2\36\1\0\2\36"+
    "\1\0\2\36\37\0\4\36\1\0\1\36\7\0\12\56"+
    "\2\0\3\36\20\0\11\36\1\0\3\36\1\0\26\36"+
    "\1\0\7\36\1\0\2\36\1\0\5\36\3\0\1\36"+
    "\22\0\1\36\17\0\2\36\4\0\12\56\11\0\1\36"+
    "\13\0\10\36\2\0\2\36\2\0\26\36\1\0\7\36"+
    "\1\0\2\36\1\0\5\36\3\0\1\36\36\0\2\36"+
    "\1\0\3\36\4\0\12\56\1\0\1\36\21\0\1\36"+
    "\1\0\6\36\3\0\3\36\1\0\4\36\3\0\2\36"+
    "\1\0\1\36\1\0\2\36\3\0\2\36\3\0\3\36"+
    "\3\0\14\36\26\0\1\36\25\0\12\56\25\0\10\36"+
    "\1\0\3\36\1\0\27\36\1\0\20\36\3\0\1\36"+
    "\32\0\3\36\5\0\2\36\4\0\12\56\20\0\1\36"+
    "\4\0\10\36\1\0\3\36\1\0\27\36\1\0\12\36"+
    "\1\0\5\36\3\0\1\36\40\0\1\36\1\0\2\36"+
    "\4\0\12\56\1\0\2\36\22\0\10\36\1\0\3\36"+
    "\1\0\51\36\2\0\1\36\20\0\1\36\5\0\3\36"+
    "\10\0\3\36\4\0\12\56\12\0\6\36\5\0\22\36"+
    "\3\0\30\36\1\0\11\36\1\0\1\36\2\0\7\36"+
    "\37\0\12\56\21\0\60\36\1\0\2\36\14\0\7\36"+
    "\11\0\12\56\47\0\2\36\1\0\1\36\1\0\5\36"+
    "\1\0\30\36\1\0\1\36\1\0\12\36\1\0\2\36"+
    "\11\0\1\36\2\0\5\36\1\0\1\36\11\0\12\56"+
    "\2\0\4\36\40\0\1\36\37\0\12\56\26\0\10\36"+
    "\1\0\44\36\33\0\5\36\163\0\53\36\24\0\1\36"+
    "\12\56\6\0\6\36\4\0\4\36\3\0\1\36\3\0"+
    "\2\36\7\0\3\36\4\0\15\36\14\0\1\36\1\0"+
    "\12\56\6\0\46\36\1\0\1\36\5\0\1\36\2\0"+
    "\53\36\1\0\u014d\36\1\0\4\36\2\0\7\36\1\0"+
    "\1\36\1\0\4\36\2\0\51\36\1\0\4\36\2\0"+
    "\41\36\1\0\4\36\2\0\7\36\1\0\1\36\1\0"+
    "\4\36\2\0\17\36\1\0\71\36\1\0\4\36\2\0"+
    "\103\36\45\0\20\36\20\0\126\36\2\0\6\36\3\0"+
    "\u016c\36\2\0\21\36\1\0\32\36\5\0\113\36\6\0"+
    "\10\36\7\0\15\36\1\0\4\36\16\0\22\36\16\0"+
    "\22\36\16\0\15\36\1\0\3\36\17\0\64\36\43\0"+
    "\1\36\4\0\1\36\3\0\12\56\46\0\12\56\6\0"+
    "\131\36\7\0\5\36\2\0\42\36\1\0\1\36\5\0"+
    "\106\36\12\0\37\36\47\0\12\56\36\36\2\0\5\36"+
    "\13\0\54\36\4\0\32\36\6\0\12\56\46\0\27\36"+
    "\11\0\65\36\53\0\12\56\6\0\12\56\15\0\1\36"+
    "\135\0\57\36\21\0\7\36\4\0\12\56\51\0\36\36"+
    "\15\0\2\36\12\56\54\36\32\0\44\36\34\0\12\56"+
    "\3\0\3\36\12\56\44\36\2\0\11\36\7\0\53\36"+
    "\2\0\3\36\51\0\4\36\1\0\6\36\1\0\2\36"+
    "\3\0\1\36\5\0\300\36\100\0\26\36\2\0\6\36"+
    "\2\0\46\36\2\0\6\36\2\0\10\36\1\0\1\36"+
    "\1\0\1\36\1\0\1\36\1\0\37\36\2\0\65\36"+
    "\1\0\7\36\1\0\1\36\3\0\3\36\1\0\7\36"+
    "\3\0\4\36\2\0\6\36\4\0\15\36\5\0\3\36"+
    "\1\0\7\36\164\0\1\36\15\0\1\36\20\0\15\36"+
    "\145\0\1\36\4\0\1\36\2\0\12\36\1\0\1\36"+
    "\3\0\5\36\6\0\1\36\1\0\1\36\1\0\1\36"+
    "\1\0\4\36\1\0\13\36\2\0\4\36\5\0\5\36"+
    "\4\0\1\36\64\0\2\36\u017b\0\57\36\1\0\57\36"+
    "\1\0\205\36\6\0\4\36\3\0\2\36\14\0\46\36"+
    "\1\0\1\36\5\0\1\36\2\0\70\36\7\0\1\36"+
    "\20\0\27\36\11\0\7\36\1\0\7\36\1\0\7\36"+
    "\1\0\7\36\1\0\7\36\1\0\7\36\1\0\7\36"+
    "\1\0\7\36\120\0\1\36\325\0\2\36\52\0\5\36"+
    "\5\0\2\36\4\0\126\36\6\0\3\36\1\0\132\36"+
    "\1\0\4\36\5\0\53\36\1\0\136\36\21\0\33\36"+
    "\65\0\306\36\112\0\360\36\20\0\215\36\103\0\56\36"+
    "\2\0\15\36\3\0\20\36\12\56\2\36\24\0\57\36"+
    "\20\0\37\36\2\0\106\36\61\0\11\36\2\0\147\36"+
    "\2\0\65\36\2\0\5\36\60\0\13\36\1\0\3\36"+
    "\1\0\4\36\1\0\27\36\35\0\64\36\16\0\62\36"+
    "\34\0\12\56\30\0\6\36\3\0\1\36\1\0\2\36"+
    "\1\0\12\56\34\36\12\0\27\36\31\0\35\36\7\0"+
    "\57\36\34\0\1\36\12\56\6\0\5\36\1\0\12\36"+
    "\12\56\5\36\1\0\51\36\27\0\3\36\1\0\10\36"+
    "\4\0\12\56\6\0\27\36\3\0\1\36\3\0\62\36"+
    "\1\0\1\36\3\0\2\36\2\0\5\36\2\0\1\36"+
    "\1\0\1\36\30\0\3\36\2\0\13\36\7\0\3\36"+
    "\14\0\6\36\2\0\6\36\2\0\6\36\11\0\7\36"+
    "\1\0\7\36\1\0\53\36\1\0\14\36\10\0\163\36"+
    "\15\0\12\56\6\0\244\36\14\0\27\36\4\0\61\36"+
    "\4\0\156\36\2\0\152\36\46\0\7\36\14\0\5\36"+
    "\5\0\1\36\1\0\12\36\1\0\15\36\1\0\5\36"+
    "\1\0\1\36\1\0\2\36\1\0\2\36\1\0\154\36"+
    "\41\0\153\36\22\0\100\36\2\0\66\36\50\0\14\36"+
    "\164\0\5\36\1\0\207\36\23\0\12\56\7\0\32\36"+
    "\6\0\32\36\13\0\131\36\3\0\6\36\2\0\6\36"+
    "\2\0\6\36\2\0\3\36\43\0\14\36\1\0\32\36"+
    "\1\0\23\36\1\0\2\36\1\0\17\36\2\0\16\36"+
    "\42\0\173\36\205\0\35\36\3\0\61\36\57\0\40\36"+
    "\15\0\24\36\1\0\10\36\6\0\46\36\12\0\36\36"+
    "\2\0\44\36\4\0\10\36\60\0\236\36\2\0\12\56"+
    "\6\0\44\36\4\0\44\36\4\0\50\36\10\0\64\36"+
    "\234\0\67\36\11\0\26\36\12\0\10\36\230\0\6\36"+
    "\2\0\1\36\1\0\54\36\1\0\2\36\3\0\1\36"+
    "\2\0\27\36\12\0\27\36\11\0\37\36\101\0\23\36"+
    "\1\0\2\36\12\0\26\36\12\0\32\36\106\0\70\36"+
    "\6\0\2\36\100\0\1\36\17\0\4\36\1\0\3\36"+
    "\1\0\35\36\52\0\35\36\3\0\35\36\43\0\10\36"+
    "\1\0\34\36\33\0\66\36\12\0\26\36\12\0\23\36"+
    "\15\0\22\36\156\0\111\36\67\0\63\36\15\0\63\36"+
    "\15\0\44\36\14\0\12\56\306\0\35\36\12\0\1\36"+
    "\10\0\26\36\232\0\27\36\14\0\65\36\56\0\12\56"+
    "\23\0\55\36\40\0\31\36\7\0\12\56\11\0\44\36"+
    "\17\0\12\56\4\0\1\36\13\0\43\36\3\0\1\36"+
    "\14\0\60\36\16\0\4\36\13\0\12\56\1\36\1\0"+
    "\1\36\43\0\22\36\1\0\31\36\124\0\7\36\1\0"+
    "\1\36\1\0\4\36\1\0\17\36\1\0\12\36\7\0"+
    "\57\36\21\0\12\56\13\0\10\36\2\0\2\36\2\0"+
    "\26\36\1\0\7\36\1\0\2\36\1\0\5\36\3\0"+
    "\1\36\22\0\1\36\14\0\5\36\236\0\65\36\22\0"+
    "\4\36\5\0\12\56\5\0\1\36\40\0\60\36\24\0"+
    "\2\36\1\0\1\36\10\0\12\56\246\0\57\36\51\0"+
    "\4\36\44\0\60\36\24\0\1\36\13\0\12\56\46\0"+
    "\53\36\15\0\1\36\7\0\12\56\66\0\33\36\25\0"+
    "\12\56\306\0\54\36\164\0\100\36\12\56\25\0\1\36"+
    "\240\0\10\36\2\0\47\36\20\0\1\36\1\0\1\36"+
    "\34\0\1\36\12\0\50\36\7\0\1\36\25\0\1\36"+
    "\13\0\56\36\23\0\1\36\42\0\71\36\7\0\11\36"+
    "\1\0\45\36\21\0\1\36\17\0\12\56\30\0\36\36"+
    "\160\0\7\36\1\0\2\36\1\0\46\36\25\0\1\36"+
    "\11\0\12\56\6\0\6\36\1\0\2\36\1\0\40\36"+
    "\16\0\1\36\7\0\12\56\u0136\0\23\36\15\0\232\36"+
    "\346\0\304\36\274\0\57\36\321\0\107\36\271\0\71\36"+
    "\7\0\37\36\1\0\12\56\146\0\36\36\22\0\60\36"+
    "\20\0\4\36\14\0\12\56\11\0\25\36\5\0\23\36"+
    "\260\0\100\36\200\0\113\36\5\0\1\36\102\0\15\36"+
    "\100\0\2\36\1\0\1\36\34\0\370\36\10\0\363\36"+
    "\15\0\37\36\61\0\3\36\21\0\4\36\10\0\u018c\36"+
    "\4\0\153\36\5\0\15\36\3\0\11\36\7\0\12\36"+
    "\146\0\125\36\1\0\107\36\1\0\2\36\2\0\1\36"+
    "\2\0\2\36\2\0\4\36\1\0\14\36\1\0\1\36"+
    "\1\0\7\36\1\0\101\36\1\0\4\36\2\0\10\36"+
    "\1\0\7\36\1\0\34\36\1\0\4\36\1\0\5\36"+
    "\1\0\1\36\3\0\7\36\1\0\u0154\36\2\0\31\36"+
    "\1\0\31\36\1\0\37\36\1\0\31\36\1\0\37\36"+
    "\1\0\31\36\1\0\37\36\1\0\31\36\1\0\37\36"+
    "\1\0\31\36\1\0\10\36\2\0\62\56\55\36\12\0"+
    "\7\36\2\0\12\56\4\0\1\36\u0171\0\54\36\4\0"+
    "\12\56\6\0\305\36\73\0\104\36\7\0\1\36\4\0"+
    "\12\56\246\0\4\36\1\0\33\36\1\0\2\36\1\0"+
    "\1\36\2\0\1\36\1\0\12\36\1\0\4\36\1\0"+
    "\1\36\1\0\1\36\6\0\1\36\4\0\1\36\1\0"+
    "\1\36\1\0\1\36\1\0\3\36\1\0\2\36\1\0"+
    "\1\36\2\0\1\36\1\0\1\36\1\0\1\36\1\0"+
    "\1\36\1\0\1\36\1\0\2\36\1\0\1\36\2\0"+
    "\4\36\1\0\7\36\1\0\4\36\1\0\4\36\1\0"+
    "\1\36\1\0\12\36\1\0\21\36\5\0\3\36\1\0"+
    "\5\36\1\0\21\36\104\0\327\36\51\0\65\36\13\0"+
    "\336\36\2\0\u0182\36\16\0\u0131\36\37\0\36\36\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\14\1\15\1\16\1\17"+
    "\1\20\1\21\16\22\1\23\1\24\1\25\1\1\1\26"+
    "\1\27\1\30\1\0\1\31\1\32\1\33\5\22\1\34"+
    "\2\22\1\35\2\22\1\36\1\37\6\22\2\0\4\22"+
    "\1\40\1\22\1\41\1\22\1\42\4\22\1\43\1\22"+
    "\1\0\4\22\1\44\5\22\1\45\1\46\1\22\1\47"+
    "\1\50\1\22\1\51\1\52\4\22\1\53\2\22\1\54"+
    "\1\22\1\55\1\56\1\57\2\22\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\57\0\57\0\215\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\274\0\353\0\u011a"+
    "\0\57\0\u0149\0\57\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\57\0\57\0\57\0\u0439\0\u0468\0\u0439"+
    "\0\u0497\0\u0439\0\57\0\57\0\57\0\u04c6\0\u04f5\0\u0524"+
    "\0\u0553\0\u0582\0\u0292\0\u05b1\0\u05e0\0\u0292\0\u060f\0\u063e"+
    "\0\u0292\0\u0292\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u0292\0\u08a1"+
    "\0\u0292\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u0292"+
    "\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0292\0\u0b04"+
    "\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0292\0\u0292\0\u0bef\0\u0292"+
    "\0\u0292\0\u0c1e\0\u0292\0\u0292\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda"+
    "\0\u0292\0\u0d09\0\u0d38\0\u0292\0\u0d67\0\u0292\0\u0292\0\u0292"+
    "\0\u0d96\0\u0dc5\0\u0292";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\2\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\3\32\1\33\2\32\1\34\1\32\1\35\1\36\1\37"+
    "\1\32\1\40\1\32\1\41\1\42\1\32\1\43\1\44"+
    "\1\45\1\46\61\0\1\3\64\0\1\47\63\0\2\16"+
    "\1\50\5\0\26\51\3\0\1\52\15\0\3\17\5\0"+
    "\26\51\3\0\1\52\23\0\1\53\56\0\1\54\56\0"+
    "\1\55\50\0\3\32\5\0\17\32\1\56\6\32\3\0"+
    "\1\32\15\0\3\32\5\0\4\32\1\57\10\32\1\60"+
    "\10\32\3\0\1\32\15\0\3\32\5\0\15\32\1\61"+
    "\10\32\3\0\1\32\15\0\3\32\5\0\10\32\1\62"+
    "\4\32\1\63\10\32\3\0\1\32\15\0\3\32\5\0"+
    "\12\32\1\64\1\32\1\65\11\32\3\0\1\32\15\0"+
    "\3\32\5\0\26\32\3\0\1\32\15\0\3\32\5\0"+
    "\5\32\1\66\6\32\1\67\11\32\3\0\1\32\15\0"+
    "\3\32\5\0\15\32\1\70\10\32\3\0\1\32\15\0"+
    "\3\32\5\0\5\32\1\71\11\32\1\72\6\32\3\0"+
    "\1\32\15\0\3\32\5\0\17\32\1\73\6\32\3\0"+
    "\1\32\15\0\3\32\5\0\4\32\1\74\21\32\3\0"+
    "\1\32\15\0\3\32\5\0\7\32\1\75\15\32\1\76"+
    "\3\0\1\32\15\0\3\32\5\0\1\77\25\32\3\0"+
    "\1\32\15\0\3\32\5\0\7\32\1\100\16\32\3\0"+
    "\1\32\15\0\3\52\5\0\26\51\3\0\1\52\10\101"+
    "\1\102\46\101\25\0\26\51\21\0\3\32\5\0\17\32"+
    "\1\103\6\32\3\0\1\32\15\0\3\32\5\0\6\32"+
    "\1\104\17\32\3\0\1\32\15\0\3\32\5\0\15\32"+
    "\1\105\10\32\3\0\1\32\15\0\3\32\5\0\14\32"+
    "\1\106\11\32\3\0\1\32\15\0\3\32\5\0\23\32"+
    "\1\107\2\32\3\0\1\32\15\0\3\32\5\0\20\32"+
    "\1\110\5\32\3\0\1\32\15\0\3\32\5\0\3\32"+
    "\1\111\22\32\3\0\1\32\15\0\3\32\5\0\21\32"+
    "\1\112\4\32\3\0\1\32\15\0\3\32\5\0\3\32"+
    "\1\113\22\32\3\0\1\32\15\0\3\32\5\0\15\32"+
    "\1\114\10\32\3\0\1\32\15\0\3\32\5\0\2\32"+
    "\1\115\23\32\3\0\1\32\15\0\3\32\5\0\4\32"+
    "\1\116\21\32\3\0\1\32\15\0\3\32\5\0\16\32"+
    "\1\117\7\32\3\0\1\32\15\0\3\32\5\0\17\32"+
    "\1\120\6\32\3\0\1\32\15\0\3\32\5\0\10\32"+
    "\1\121\15\32\3\0\1\32\10\101\1\122\46\101\7\0"+
    "\1\3\1\102\63\0\3\32\5\0\1\123\25\32\3\0"+
    "\1\32\15\0\3\32\5\0\10\32\1\124\15\32\3\0"+
    "\1\32\15\0\3\32\5\0\12\32\1\125\13\32\3\0"+
    "\1\32\15\0\3\32\5\0\20\32\1\126\5\32\3\0"+
    "\1\32\15\0\3\32\5\0\4\32\1\127\3\32\1\130"+
    "\15\32\3\0\1\32\15\0\3\32\5\0\4\32\1\131"+
    "\21\32\3\0\1\32\15\0\3\32\5\0\22\32\1\132"+
    "\3\32\3\0\1\32\15\0\3\32\5\0\2\32\1\133"+
    "\23\32\3\0\1\32\15\0\3\32\5\0\15\32\1\134"+
    "\10\32\3\0\1\32\15\0\3\32\5\0\14\32\1\135"+
    "\11\32\3\0\1\32\15\0\3\32\5\0\4\32\1\136"+
    "\21\32\3\0\1\32\15\0\3\32\5\0\12\32\1\137"+
    "\13\32\3\0\1\32\7\101\1\3\1\122\46\101\15\0"+
    "\3\32\5\0\25\32\1\140\3\0\1\32\15\0\3\32"+
    "\5\0\14\32\1\141\11\32\3\0\1\32\15\0\3\32"+
    "\5\0\4\32\1\142\21\32\3\0\1\32\15\0\3\32"+
    "\5\0\21\32\1\143\4\32\3\0\1\32\15\0\3\32"+
    "\5\0\5\32\1\144\20\32\3\0\1\32\15\0\3\32"+
    "\5\0\6\32\1\145\17\32\3\0\1\32\15\0\3\32"+
    "\5\0\12\32\1\146\13\32\3\0\1\32\15\0\3\32"+
    "\5\0\4\32\1\147\21\32\3\0\1\32\15\0\3\32"+
    "\5\0\17\32\1\150\6\32\3\0\1\32\15\0\3\32"+
    "\5\0\4\32\1\151\21\32\3\0\1\32\15\0\3\32"+
    "\5\0\1\152\25\32\3\0\1\32\15\0\3\32\5\0"+
    "\4\32\1\153\21\32\3\0\1\32\15\0\3\32\5\0"+
    "\4\32\1\154\21\32\3\0\1\32\15\0\3\32\5\0"+
    "\3\32\1\155\22\32\3\0\1\32\15\0\3\32\5\0"+
    "\3\32\1\156\22\32\3\0\1\32\15\0\3\32\5\0"+
    "\14\32\1\157\11\32\3\0\1\32\15\0\3\32\5\0"+
    "\17\32\1\160\6\32\3\0\1\32\15\0\3\32\5\0"+
    "\22\32\1\161\3\32\3\0\1\32\15\0\3\32\5\0"+
    "\17\32\1\162\6\32\3\0\1\32\15\0\3\32\5\0"+
    "\4\32\1\163\21\32\3\0\1\32";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3572];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\1\1\6\11\3\1\1\11"+
    "\1\1\1\11\17\1\3\11\4\1\1\0\3\11\23\1"+
    "\2\0\17\1\1\0\41\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
int get_line(){return yyline;}
int get_column() {return yycolumn;}


private java_cup.runtime.Symbol CreateSYM(int type)
{
    return new java_cup.runtime.Symbol(type);
}
private java_cup.runtime.Symbol CreateSYM(int type, Object value)
{
    return new java_cup.runtime.Symbol(type, value);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return CreateSYM(Sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalSymbolException(yytext());
            }
            // fall through
          case 49: break;
          case 2:
            { 
            }
            // fall through
          case 50: break;
          case 3:
            { return CreateSYM(Sym.NEQUAL);
            }
            // fall through
          case 51: break;
          case 4:
            { return CreateSYM(Sym.AND);
            }
            // fall through
          case 52: break;
          case 5:
            { return CreateSYM(Sym.LPATH);
            }
            // fall through
          case 53: break;
          case 6:
            { return CreateSYM(Sym.RPATH);
            }
            // fall through
          case 54: break;
          case 7:
            { return CreateSYM(Sym.MUL);
            }
            // fall through
          case 55: break;
          case 8:
            { return CreateSYM(Sym.ADD);
            }
            // fall through
          case 56: break;
          case 9:
            { return CreateSYM(Sym.COMMA);
            }
            // fall through
          case 57: break;
          case 10:
            { return CreateSYM(Sym.MINUS);
            }
            // fall through
          case 58: break;
          case 11:
            { return CreateSYM(Sym.DOT);
            }
            // fall through
          case 59: break;
          case 12:
            { if (yylength() > 12)
            throw new IllegalIntegerRangeException(yytext());
        return CreateSYM(Sym.DIGIT, Integer.parseInt(yytext()));
            }
            // fall through
          case 60: break;
          case 13:
            { return CreateSYM(Sym.COLON);
            }
            // fall through
          case 61: break;
          case 14:
            { return CreateSYM(Sym.SEMI);
            }
            // fall through
          case 62: break;
          case 15:
            { return CreateSYM(Sym.LESS);
            }
            // fall through
          case 63: break;
          case 16:
            { return CreateSYM(Sym.EQUAL);
            }
            // fall through
          case 64: break;
          case 17:
            { return CreateSYM(Sym.MORE);
            }
            // fall through
          case 65: break;
          case 18:
            { if (yylength() > 24)
            throw new IllegalIdentifierLengthException(yytext());
        return CreateSYM(Sym.IDENTIFIER, yytext().toLowerCase());
            }
            // fall through
          case 66: break;
          case 19:
            { return CreateSYM(Sym.LBRACK);
            }
            // fall through
          case 67: break;
          case 20:
            { return CreateSYM(Sym.RBRACK);
            }
            // fall through
          case 68: break;
          case 21:
            { return CreateSYM(Sym.NOT);
            }
            // fall through
          case 69: break;
          case 22:
            { throw new MismatchedCommentException(yytext());
            }
            // fall through
          case 70: break;
          case 23:
            { throw new IllegalOctalException(yytext());
            }
            // fall through
          case 71: break;
          case 24:
            { throw new IllegalIntegerException(yytext());
            }
            // fall through
          case 72: break;
          case 25:
            { return CreateSYM(Sym.ASSIGN);
            }
            // fall through
          case 73: break;
          case 26:
            { return CreateSYM(Sym.ELESS);
            }
            // fall through
          case 74: break;
          case 27:
            { return CreateSYM(Sym.EMORE);
            }
            // fall through
          case 75: break;
          case 28:
            { return CreateSYM(Sym.DO);
            }
            // fall through
          case 76: break;
          case 29:
            { return CreateSYM(Sym.IF);
            }
            // fall through
          case 77: break;
          case 30:
            { return CreateSYM(Sym.OF);
            }
            // fall through
          case 78: break;
          case 31:
            { return CreateSYM(Sym.OR);
            }
            // fall through
          case 79: break;
          case 32:
            { return CreateSYM(Sym.DIV);
            }
            // fall through
          case 80: break;
          case 33:
            { return CreateSYM(Sym.END);
            }
            // fall through
          case 81: break;
          case 34:
            { return CreateSYM(Sym.MOD);
            }
            // fall through
          case 82: break;
          case 35:
            { return CreateSYM(Sym.VAR);
            }
            // fall through
          case 83: break;
          case 36:
            { return CreateSYM(Sym.ELSE);
            }
            // fall through
          case 84: break;
          case 37:
            { return CreateSYM(Sym.THEN);
            }
            // fall through
          case 85: break;
          case 38:
            { return CreateSYM(Sym.TYPE);
            }
            // fall through
          case 86: break;
          case 39:
            { return CreateSYM(Sym.ARRAY);
            }
            // fall through
          case 87: break;
          case 40:
            { return CreateSYM(Sym.BEGIN);
            }
            // fall through
          case 88: break;
          case 41:
            { return CreateSYM(Sym.CONST);
            }
            // fall through
          case 89: break;
          case 42:
            { return CreateSYM(Sym.ELSIF);
            }
            // fall through
          case 90: break;
          case 43:
            { return CreateSYM(Sym.WHILE);
            }
            // fall through
          case 91: break;
          case 44:
            { return CreateSYM(Sym.MODULE);
            }
            // fall through
          case 92: break;
          case 45:
            { return CreateSYM(Sym.RECORD);
            }
            // fall through
          case 93: break;
          case 46:
            { return CreateSYM(Sym.BOOLEAN);
            }
            // fall through
          case 94: break;
          case 47:
            { return CreateSYM(Sym.INTEGER);
            }
            // fall through
          case 95: break;
          case 48:
            { return CreateSYM(Sym.PROCEDURE);
            }
            // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
