
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int CONST = 19;
  public static final int EMORE = 7;
  public static final int ELSIF = 29;
  public static final int INTEGER = 32;
  public static final int SEMI = 37;
  public static final int ARRAY = 23;
  public static final int LESS = 4;
  public static final int MINUS = 9;
  public static final int NOT = 15;
  public static final int AND = 14;
  public static final int RECORD = 22;
  public static final int LPATH = 34;
  public static final int TYPE = 20;
  public static final int OR = 10;
  public static final int COMMA = 39;
  public static final int ELESS = 5;
  public static final int DIV = 12;
  public static final int BEGIN = 17;
  public static final int DIGIT = 43;
  public static final int ASSIGN = 40;
  public static final int IF = 27;
  public static final int DOT = 36;
  public static final int OF = 24;
  public static final int EOF = 0;
  public static final int BOOLEAN = 33;
  public static final int EQUAL = 2;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int ADD = 8;
  public static final int MOD = 13;
  public static final int LBRACK = 41;
  public static final int MODULE = 16;
  public static final int COLON = 38;
  public static final int RPATH = 35;
  public static final int ELSE = 30;
  public static final int RBRACK = 42;
  public static final int WHILE = 25;
  public static final int NEQUAL = 3;
  public static final int THEN = 28;
  public static final int END = 18;
  public static final int VAR = 21;
  public static final int PROCEDURE = 31;
  public static final int MORE = 6;
  public static final int DO = 26;
  public static final int IDENTIFIER = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQUAL",
  "NEQUAL",
  "LESS",
  "ELESS",
  "MORE",
  "EMORE",
  "ADD",
  "MINUS",
  "OR",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "NOT",
  "MODULE",
  "BEGIN",
  "END",
  "CONST",
  "TYPE",
  "VAR",
  "RECORD",
  "ARRAY",
  "OF",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "PROCEDURE",
  "INTEGER",
  "BOOLEAN",
  "LPATH",
  "RPATH",
  "DOT",
  "SEMI",
  "COLON",
  "COMMA",
  "ASSIGN",
  "LBRACK",
  "RBRACK",
  "DIGIT",
  "IDENTIFIER"
  };
}

